*** how-to-deal-with-this-error-1049-unknown-database-users-ohyunjun-work-astra ***

 In the Django  , I set databases option this way 
 
 And I executed this command 
 
 python manage.py syncdb 
 
 But failed with this error 
 
 
  is the name of your database. With MySQL, you need to manually create your database too. Let's say, if you run: 
 
 your configuration should be: 
 
 