*** knex-transaction-with-promises ***

 I am getting the correct output, and indeed, these two operations are being treated as a single transactional unit; where if one fails, both fail. 
 In this code example: i am doing a transaction of 
 (1) insert
(2) update 
 The way I approach it is to nest my db operations inside the .then.
My question is if this code is correct by accident? i am new to promises and knex. 
 
 This works, but I feel like I am doing something wrong still. Looking for comments. 
 
 You need to return a promise from the inner query in order for the outer chain to be chained with that. 
 You also swallow any errors because you don't rethrow them - it's better to use   for this reason because it makes it more clearer what is happening - that is what would happen with normal   statement.  
 
 To understand it better, here's the synchronous version that is being "emulated": 
 
 