*** oserror-errno-18-invalid-cross-device-link ***

 I'm working with django 1.6.5 and python 2.7.
I have import feature in my app and I get error: 
 
 I have problem with this part of code: 
 
 code in settings: 
 
 
  only works if source and destination are on the same file system. You should use   instead. 
 
 I think rename only works when the source and target names are on the same file system. You probably have different mounts. Otherwise you get that error. You can implement the same effect with a copy and a delete. 
 Hope it helps 
 